services:

  postgres:
    image: postgres:16-alpine
    container_name: mpladsentinel-postgres-dev

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mpladsentinel}
      POSTGRES_USER: ${POSTGRES_USER:-mpladsentinel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me-locally}

    # For production, remove this unless you need external DB access.
    ports:
      - "${POSTGRES_PORT:-5544}:5432"

    volumes:
      - mpladsentinel-pgdata:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-mpladsentinel} -d ${POSTGRES_DB:-mpladsentinel}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    container_name: mpladsentinel-backend-dev

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      MPLADS_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-mpladsentinel}
      MPLADS_DB_USERNAME: ${POSTGRES_USER:-mpladsentinel}
      MPLADS_DB_PASSWORD: ${POSTGRES_PASSWORD:-change-me-locally}
      SPRING_PROFILES_ACTIVE: prod
      MPLADS_CORS_ALLOWED_ORIGINS: https://mplad-sentinel-two.vercel.app
    ports:
      - "8081:8081"


  nginx:
    image: nginx:latest
    container_name: nginx_dev
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend



volumes:
  mpladsentinel-pgdata: