services:

  postgres:
    image: postgres:16-alpine
    container_name: mpladsentinel-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mpladsentinel}
      POSTGRES_USER: ${POSTGRES_USER:-mpladsentinel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me-locally}

    ports:
      - "${POSTGRES_PORT:-5544}:5432"

    volumes:
      - mpladsentinel-pgdata:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-mpladsentinel} -d ${POSTGRES_DB:-mpladsentinel}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    container_name: mpladsentinel-backend

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      MPLADS_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-mpladsentinel}
      MPLADS_DB_USERNAME: ${POSTGRES_USER:-mpladsentinel}
      MPLADS_DB_PASSWORD: ${POSTGRES_PASSWORD:-change-me-locally}

    ports:
      - "8081:8081"


  nginx:
    image: nginx:latest
    container_name: nginx_prod
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro

      - ./certbot/www:/var/www/certbot

      - /etc/letsencrypt/live/parthakadam.in/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/parthakadam.in/privkey.pem:/etc/nginx/ssl/privkey.pem:ro


  certbot:
    image: certbot/certbot

    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt


volumes:
  mpladsentinel-pgdata: